// 05.UX-SPA/Angular/app3/src/app/account-holders/account-holders.component.ts
import { Component, OnInit } from '@angular/core';
import { AccountHolder } from '../models/account-holder';
import { AccountHoldersService } from '../services/account-holders.service';

@Component({
  selector: 'app-account-holders',
  templateUrl: './account-holders.component.html',
  styleUrls: ['./account-holders.component.css']
})
export class AccountHoldersComponent implements OnInit {

  accounts!:AccountHolder[];
  errMsg!:string;

  constructor(private ahs:AccountHoldersService) { }

  ngOnInit(): void {
    this.loadData();
  }

  loadData(){
    let ob = this.ahs.getAllAccounts();

    ob.subscribe({
      next: data => this.accounts=data,
      error: err => {console.error(err); this.errMsg="Unable to load data, Please retry later!";}
    });
  }
}

<div class="col-sm-9 p-2 mx-auto">
    <h5>Accounts</h5>

    <p class="alert alert-info p-3 fw-bold" *ngIf="!accounts && !errMsg">
        Please wait while loading data...
    </p>

    <p class="alert alert-danger p-3 fw-bold" *ngIf="errMsg">
        {{errMsg}}
    </p>

    <p class="alert alert-info p-3 fw-bold" *ngIf="accounts && accounts.length===0">
        No records to display
    </p>

    <table class="table table-border table-striped table-hover" *ngIf="accounts && accounts.length>0">
        <thead>
            <tr>
                <th>Account#</th>
                <th>Full Name</th>
                <th>Mobile</th>
                <th>Mail</th>
                <th>Balance</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let a of accounts">
                <td class="text-end">{{a.ahId|number:'3.0-0'}}</td>
                <td>{{a.fullName|uppercase}}</td>
                <td>{{a.mobile}}</td>
                <td>{{a.mailId}}</td>
                <td class="text-end">{{a.currentBalance|currency:'INR'}}</td>
                <td>
                    <a [routerLink]="['/editAccount',a.ahId]" class="btn btn-sm btn-primary me-1">
                        EDIT
                    </a>
                    <a [routerLink]="['/statement',a.ahId]" class="btn btn-sm btn-secondary">
                        STATEMENT
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
</div>

// 05.UX-SPA/ReactJS/app6/src/components/AccountHolders.js
import { useEffect, useState } from 'react';
import AccountHolder from '../models/AccountHolder';
import AhForm from './AhForm';
import AhRow from './AhRow';
import AHService from '../services/AHService';

const AccountHolders = () => {

    let [ahs, setAhs] = useState(null);
    let [errMsg, setErrMsg] = useState(null);

    const loadData = () => {
        AHService.getAllAccounts()
            .then(resp => { setAhs(resp.data); setErrMsg(null) })
            .catch(err => { console.error(err); setErrMsg("Unable To Load Data! Please Retry Later!") });
    }

    useEffect(loadData, []);

    const add = ah => {
        AHService.addAccount(ah)
            .then(resp => loadData())
            .catch(err => { console.error(err); setErrMsg("Unable To Save Data! Please Retry Later!") });
    };

    const makeEditable = ahId => setAhs(ahs.map(ah => ah.ahId === ahId ? { ...ah, isEditable: true } : ah))

    const cancelEditable = ahId => setAhs(ahs.map(ah => ah.ahId === ahId ? { ...ah, isEditable: undefined } : ah))

    const update = ahToBeSaved => {
        AHService.updateAccount({ ...ahToBeSaved, isEditable: undefined })
            .then(resp => loadData())
            .catch(err => { console.error(err); setErrMsg("Unable To Save Data! Please Retry Later!") });
    };

    return (
        <section className='container-fluid p-4'>
            <h4>Account Holders</h4>

            {(!ahs && !errMsg) &&
                <p className="alert alert-info p-4">
                    Loading Please wait...
                </p>
            }

            {(ahs && ahs.length === 0) &&
                <p className="alert alert-info p-4">
                    No Account Holder Records Available To Display
                </p>
            }

            {errMsg &&
                <p className="alert alert-danger p-4">
                    {errMsg}
                </p>
            }

            <table className='table table-bordered table-striped table-hover'>
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Mail Id</th>
                        <th>Mobile</th>
                        <th>Balance</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <AhForm add={add} />
                    {(ahs && ahs.length > 0) &&
                        ahs.map(
                            ah => ah.isEditable ?
                                <AhForm ah={ah}
                                    key={ah.ahId}
                                    update={update}
                                    cancelEditable={cancelEditable} /> :
                                <AhRow ah={ah}
                                    key={ah.ahId}
                                    makeEditable={makeEditable} />
                        )
                    }
                </tbody>
            </table>

        </section>
    );
}

export default AccountHolders;
