// 05.UX-SPA/Angular/app3/src/app/txn-row/txn-row.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Txn } from '../models/txn';

@Component({
  selector: 'app-txn-row',
  templateUrl: './txn-row.component.html',
  styleUrls: ['./txn-row.component.css']
})
export class TxnRowComponent implements OnInit {

  @Input()
  txn!:Txn;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="row border-bottom p-1">
    <div class="col-sm-1 text-end">
        {{txn.txnId}}
    </div>
    <div class="col-sm-2 text-center">
        {{txn.txnDate|date:'dd-MMM-yyyy'}}
    </div>
    <div class="col">
        {{txn.desp}}
    </div>
    <div class="col-sm-2 text-end">
        <span *ngIf="txn.type==='CREDIT'">{{txn.amount|currency:'INR'}}</span>
    </div>
    <div class="col-sm-2 text-end">
        <span *ngIf="txn.type==='DEBIT'">{{txn.amount|currency:'INR'}}</span>
    </div>
    <div class="col-sm-2">
        <button type="button" class="btn btn-sm btn-info me-1">EDIT</button>
        <button type="button" class="btn btn-sm btn-danger">DELETE</button>
    </div>
</div>

// 05.UX-SPA/ReactJS/app10/src/txns/components/TxnRow.js
import { Link } from 'react-router-dom';
import { useDispatch } from 'react-redux';
import { createMarkEditTxnAction,createDeleteTxnActionThunk } from '../stateManagement/txnReducer';
const TxnRow = ({ txn }) => {

    const dispatch = useDispatch();
    return (
        <tr>
            <td>{txn.txnId}</td>
            <td>{txn.txnDate}</td>
            <td>{txn.desp}</td>
            <td className='text-end'>{txn.type === 'CREDIT' ? txn.amount : ''}</td>
            <td className='text-end'>{txn.type === 'DEBIT' ? txn.amount : ''}</td>
            <td>
                <button className='btn btn-sm btn-secondary'
                    onClick={e => dispatch(createMarkEditTxnAction(txn.txnId))}>
                    EDIT
                </button>
                <button className='btn btn-sm btn-danger'
                    onClick={e => dispatch(createDeleteTxnActionThunk(txn))}>
                    DELETE
                </button>

            </td>
        </tr>
    );
}

export default TxnRow;
